# Generated by Django 4.1.3 on 2023-04-24 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phonenumber', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('opentime', models.SmallIntegerField(choices=[(0, '8:00'), (1, '8:30'), (2, '9:00'), (3, '9:30'), (4, '10:00'), (5, '10:30'), (6, '11:00')], default=4)),
                ('closetime', models.SmallIntegerField(choices=[(0, '16:00'), (1, '16:30'), (2, '17:00'), (3, '18:00'), (4, '19:00'), (5, '20:00'), (6, '21:00'), (7, '22:00'), (8, '23:00'), (9, '23:30')], default=5)),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
            ],
        ),
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('SN', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('onshelf', models.BooleanField(default=True)),
                ('supper', models.BooleanField(default=True)),
                ('picture', models.ImageField(upload_to='pic/', verbose_name='图片地址')),
                ('createdate', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supports.restaurant')),
            ],
        ),
    ]
