# Generated by Django 4.1.3 on 2023-04-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='pic/', verbose_name='Photo of Restaurant'),
        ),
    ]
