# Generated by Django 4.1.3 on 2023-04-24 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('supports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('createdate', models.DateTimeField(verbose_name='order date')),
                ('quantity', models.IntegerField(default=1)),
                ('spicy', models.SmallIntegerField(choices=[(0, '免辣'), (1, '微辣'), (2, '中辣'), (3, '重辣'), (4, '超辣')], default=0)),
                ('dinnertime', models.SmallIntegerField(choices=[(0, '午餐'), (1, '晚餐')], default=0)),
                ('dish', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='supports.dish')),
            ],
        ),
    ]
